"""Descriptive climatology atlas of hurricane-force (HF) lows, per basin and month.

usage: python3 -I research/era5/climatology_atlas/atlas.py            (writes results/)

Two sources, always labelled:
  archive   OPC hurricane-force archive on main, via docs/data/hf-lows.json (generated by
            tools/build_hf_lows.py). HF-window metrics only: recording practice changed in 2013-14 (Pacific) and
            2017-18 (Atlantic), so the whole-track metrics are not comparable across seasons.
  proxy     ERA5 pipeline A (research/era5/hf_history), a PROXY: an event is a cyclone whose ERA5 800 km ocean
            gust index reaches 71.7 kt. Committed files only (catalog, catalog tracks, lifecycle_events).

Sample: seasons 2004-05 to 2025-26 (22 seasons; season = 1 June to 31 May, labelled by its start year).
Decision 1: nothing before 2004-05 is used. No trend is estimated here. Tropical-cyclone-linked events are
INCLUDED in every count and distribution (the archive cannot separate them); the proxy's TC-linked share is shown.
An HF event is an archive low with at least one HF-category fix, or a pipeline A event. The month of an event is
the month of its first HF fix. Uncertainty: 95% intervals from a season-block bootstrap (seasons resampled with
replacement within basin, 2,000 draws, seed 1). These are descriptive statistics: no hypothesis is tested.
"""
import json
import os
import sys
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
RES = os.path.join(HERE, "results")
HFH = os.path.join(ROOT, "research", "era5", "hf_history", "results")
THR = 71.7
FIRST, LAST = 2004, 2025          # season start years
NSEAS = LAST - FIRST + 1
NBOOT = 2000
MONTHS = [10, 11, 12, 1, 2, 3, 4]  # Oct-Apr: where nearly all HF lows are
BASINS = ("atl", "pac")
BN = {"atl": "Atlantic", "pac": "Pacific"}


def lonfix(lon, basin):
    lon = np.asarray(lon, float)
    return ((lon + 180) % 360) - 180 if basin == "atl" else lon % 360


# ----------------------------------------------------------------------------- loading
def load_archive():
    d = json.load(open(os.path.join(ROOT, "docs", "data", "hf-lows.json")))
    ev, fx = [], []
    for raw in d["lows"]:
        l = dict(zip(d["lowFields"], raw))
        if l["season"] < FIRST:
            continue
        key = f'{l["basin"]}:{l["id"]}'
        f = pd.DataFrame(l["fixes"], columns=["date", "lat", "lon", "cat", "pres"])
        f["t"] = pd.to_datetime(f.date.astype("int64").astype(str), format="%Y%m%d%H")
        f = f.drop_duplicates("t").sort_values("t")
        h = f[f.cat == "HF"]
        if h.empty:
            continue
        b = l["basin"]
        i_min = f.pres.astype(float).idxmin() if f.pres.notna().any() else None
        e = dict(key=key, basin=b, season=l["season"], cls=l["cls"], minp=l["minP"] if l["cls"] == "low" else np.nan,
                 mon_on=h.t.iloc[0].month, hf_h=6.0 * len(h), hf_dist_km=l["hfDistNm"] * 1.852 if l["hfDistNm"] is not None else np.nan,
                 hf_spd=l["hfSpdKt"], deep24=l["deep24"], berg=l["berg"], bomb=l["bomb"],
                 lat_on=h.lat.iloc[0], lon_on=lonfix(h.lon.iloc[0], b), t_on=h.t.iloc[0],
                 lat_off=h.lat.iloc[-1], lon_off=lonfix(h.lon.iloc[-1], b),
                 lat_mp=l["minPLat"] if l["cls"] == "low" else np.nan,
                 lon_mp=lonfix(l["minPLon"], b) if (l["cls"] == "low" and l["minPLon"] is not None) else np.nan,
                 minpat=l["minPAt"])
        ev.append(e)
        hh = h.copy()
        hh["key"], hh["basin"], hh["season"] = key, b, l["season"]
        hh["lon"] = lonfix(hh.lon, b)
        fx.append(hh[["key", "basin", "season", "t", "lat", "lon"]])
    return pd.DataFrame(ev), pd.concat(fx, ignore_index=True)


def load_proxy(first=FIRST, last=LAST):
    C = pd.read_csv(os.path.join(HFH, "era5_hf_catalog.csv"))
    E = C[(C.role == "event") & (C.season >= first) & (C.season <= last)].set_index("track")
    T = pd.read_csv(os.path.join(HFH, "era5_hf_catalog_tracks.csv"))
    T = T[T.track.isin(E.index)].copy()
    T["t"] = pd.to_datetime(T.time.astype(str), format="%Y%m%d%H")
    T["indom"] = T.basin.fillna("") != ""
    T = T.sort_values(["track", "t"]).reset_index(drop=True)
    LC = pd.read_csv(os.path.join(HFH, "lifecycle_events.csv")).set_index("track")
    ev, fx = [], []
    for tr, g in T.groupby("track"):
        b = E.basin[tr]
        hf = g[g.indom & (g.g800 >= THR)]
        if hf.empty:
            continue
        i_mp = g.msl.idxmin()
        lc = LC.loc[tr] if tr in LC.index else None
        ev.append(dict(key=f"{b}:{tr}", track=tr, basin=b, season=int(E.season[tr]), minp=g.msl.min(),
                       gust=E.gust800_kt[tr], mon_on=hf.t.iloc[0].month, hf_h=6.0 * len(hf),
                       lat_on=hf.lat.iloc[0], lon_on=lonfix(hf.lon.iloc[0], b), t_on=hf.t.iloc[0],
                       lat_off=hf.lat.iloc[-1], lon_off=lonfix(hf.lon.iloc[-1], b),
                       lat_mp=g.lat[i_mp], lon_mp=lonfix(g.lon[i_mp], b),
                       lat_pg=E.peak_lat[tr], lon_pg=lonfix(E.peak_lon[tr], b),
                       tc=bool(lc.tc) if lc is not None else np.nan,
                       maxdeep=lc.maxdeep if lc is not None else np.nan,
                       hf_spd=lc.spd_hf if lc is not None else np.nan,
                       gen_obs=bool(lc.gen_obs) if lc is not None else np.nan))
        h = hf.copy()
        h["key"], h["basin"], h["season"] = f"{b}:{tr}", b, int(E.season[tr])
        h["lon"] = lonfix(h.lon, b)
        fx.append(h[["key", "basin", "season", "t", "lat", "lon"]])
    return pd.DataFrame(ev), pd.concat(fx, ignore_index=True), T, E


# ----------------------------------------------------------------------------- bootstrap helpers
def boot_seasons(df, fn, basin_col="basin", seed=1, basins=BASINS):
    """fn(DataFrame)->dict of scalars. Returns point estimate and 95% interval per key, per basin, resampling seasons
    within basin."""
    rng = np.random.default_rng(seed)
    out = {}
    for b in basins:
        d = df[df[basin_col] == b]
        groups = {s: g for s, g in d.groupby("season")}
        seasons = np.array(list(range(FIRST, LAST + 1)))
        pt = fn(d)
        draws = []
        for _ in range(NBOOT):
            pick = rng.choice(seasons, NSEAS)
            parts = [groups[s] for s in pick if s in groups]
            draws.append(fn(pd.concat(parts)))
        res = {}
        for k in pt:
            arr = np.array([x[k] for x in draws], float)
            res[k] = (pt[k], np.nanpercentile(arr, 2.5), np.nanpercentile(arr, 97.5))
        out[b] = res
    return out


def fmt(t, nd=1):
    return f"{t[0]:.{nd}f} [{t[1]:.{nd}f}, {t[2]:.{nd}f}]"


# ----------------------------------------------------------------------------- products
def monthly_table(ev, src):
    """Events and HF hours per season, by month of first HF fix, with intervals (season-block bootstrap)."""
    rng = np.random.default_rng(1)
    rows = []
    for b in BASINS:
        d = ev[ev.basin == b]
        cnt = np.zeros((NSEAS, len(MONTHS)))
        hrs = np.zeros((NSEAS, len(MONTHS)))
        for j, m in enumerate(MONTHS):
            x = d[d.mon_on == m]
            cnt[:, j] = x.groupby("season").size().reindex(range(FIRST, LAST + 1), fill_value=0).values
            hrs[:, j] = x.groupby("season").hf_h.sum().reindex(range(FIRST, LAST + 1), fill_value=0).values
        idx = rng.integers(0, NSEAS, (NBOOT, NSEAS))
        bc, bh = cnt[idx].mean(1), hrs[idx].mean(1)
        for j, m in enumerate(MONTHS):
            rows.append(dict(source=src, basin=b, month=m, events_per_season=cnt[:, j].mean(),
                             ev_lo=np.percentile(bc[:, j], 2.5), ev_hi=np.percentile(bc[:, j], 97.5),
                             hf_hours_per_season=hrs[:, j].mean(), h_lo=np.percentile(bh[:, j], 2.5),
                             h_hi=np.percentile(bh[:, j], 97.5), events_total=int(cnt[:, j].sum())))
    return pd.DataFrame(rows)


def season_table(ev, src):
    rows = []
    for b in BASINS:
        for s in range(FIRST, LAST + 1):
            x = ev[(ev.basin == b) & (ev.season == s)]
            rows.append(dict(source=src, basin=b, season=s, events=len(x), hf_hours=x.hf_h.sum()))
    return pd.DataFrame(rows)


def dist_summary(ev, src, cols):
    rows = []
    for b in BASINS:
        for c in cols:
            def fn(x, c=c):
                v = x[c].astype(float).dropna()
                return dict(median=v.median(), q25=v.quantile(.25), q75=v.quantile(.75), p90=v.quantile(.9), mean=v.mean())
            r = boot_seasons(ev, fn, basins=(b,))[b]
            n = int(ev[(ev.basin == b)][c].notna().sum())
            rows.append(dict(source=src, basin=b, metric=c, n=n,
                             **{f"{k}": r[k][0] for k in r}, median_lo=r["median"][1], median_hi=r["median"][2]))
    return pd.DataFrame(rows)


def box_hours(fx, basin):
    """HF-centre hours per season in 5 deg lat x 10 deg lon boxes."""
    f = fx[fx.basin == basin]
    lon_edges = np.arange(-100, 31, 10) if basin == "atl" else np.arange(120, 251, 10)
    lat_edges = np.arange(20, 76, 5)
    H, _, _ = np.histogram2d(f.lat, f.lon, bins=[lat_edges, lon_edges])
    return lat_edges, lon_edges, H * 6.0 / NSEAS


def simultaneity(fx, src):
    """Share of 6-hourly times (Oct-Apr, 22 seasons) with k or more distinct HF lows active in a basin."""
    rows = []
    for b in BASINS:
        f = fx[(fx.basin == b) & fx.t.dt.month.isin(MONTHS)]
        n = f.groupby("t").key.nunique()
        total = 0
        for s in range(FIRST, LAST + 1):
            total += len(pd.date_range(f"{s}-10-01", f"{s + 1}-04-30 18:00", freq="6h"))
        row = dict(source=src, basin=b, times_total=total, max_simultaneous=int(n.max()))
        for k in (1, 2, 3, 4):
            row[f"share_ge{k}"] = float((n >= k).sum() / total)
        row["mean_given_any"] = float(n.mean())
        rows.append(row)
    return pd.DataFrame(rows)


def motion_field(fx):
    """Mean 6-hourly displacement between consecutive HF fixes of one low, in 5 x 10 degree boxes."""
    f = fx.sort_values(["key", "t"]).copy()
    g = f.groupby("key")
    f["dt"] = g.t.diff().dt.total_seconds() / 3600
    f["lat0"], f["lon0"] = g.lat.shift(), g.lon.shift()
    f = f[f.dt == 6]
    dlon = (f.lon - f.lon0 + 180) % 360 - 180
    f["u"] = dlon * 111.19 * np.cos(np.radians((f.lat + f.lat0) / 2)) / 6 / 1.852   # kt east
    f["v"] = (f.lat - f.lat0) * 111.19 / 6 / 1.852                                     # kt north
    f["latc"] = (f.lat + f.lat0) / 2
    f["lonc"] = f.lon0 + dlon / 2
    return f


def main():
    os.makedirs(RES, exist_ok=True)
    A, AF = load_archive()
    P, PF, T, E = load_proxy()
    out = []
    w = out.append
    w("Climatology atlas of hurricane-force lows. ARCHIVE = OPC archive (HF-window metrics); PROXY = ERA5 pipeline A, a proxy.")
    w(f"Seasons {FIRST}-{str(FIRST + 1)[2:]} to {LAST}-{str(LAST + 1)[2:]} ({NSEAS} seasons). Tropical-cyclone-linked events included. Brackets: 95% season-block bootstrap.")
    w(f"Events: archive {len(A)} (atl {int((A.basin=='atl').sum())}, pac {int((A.basin=='pac').sum())}); proxy {len(P)} (atl {int((P.basin=='atl').sum())}, pac {int((P.basin=='pac').sum())}).")
    w(f"Archive classes: " + ", ".join(f"{k} {v}" for k, v in A.cls.value_counts().items()) + ". Pressure statistics use class 'low' only.")
    w(f"Proxy events linked to a tropical cyclone (400 km, IBTrACS proximity; first look, not the tightened definition): atl {P[P.basin=='atl'].tc.mean():.3f}, pac {P[P.basin=='pac'].tc.mean():.3f}.")

    # ---- 2. monthly exposure
    mt = pd.concat([monthly_table(A, "archive"), monthly_table(P, "proxy")])
    mt.to_csv(os.path.join(RES, "monthly_exposure.csv"), index=False, float_format="%.3f")
    w("\n== Monthly exposure: events and HF hours per season, by month of first HF fix ==")
    for b in BASINS:
        for src in ("archive", "proxy"):
            s = mt[(mt.source == src) & (mt.basin == b)]
            w(f"-- {BN[b]} {src}")
            for _, r in s.iterrows():
                w(f"   month {int(r.month):2d}: events {r.events_per_season:.2f} [{r.ev_lo:.2f}, {r.ev_hi:.2f}]   HF hours {r.hf_hours_per_season:.1f} [{r.h_lo:.1f}, {r.h_hi:.1f}]")
    for src, ev in (("archive", A), ("proxy", P)):
        for b in BASINS:
            d = ev[ev.basin == b]
            inwin = d.mon_on.isin(MONTHS).mean()
            w(f"Share of {src} {BN[b]} events with first HF fix in Oct-Apr: {inwin:.3f}")

    # ---- interannual
    st = pd.concat([season_table(A, "archive"), season_table(P, "proxy")])
    st.to_csv(os.path.join(RES, "season_counts.csv"), index=False)
    w("\n== Season-to-season: events per season ==")
    for src in ("archive", "proxy"):
        for b in BASINS:
            v = st[(st.source == src) & (st.basin == b)].set_index("season").events
            top = v.sort_values(ascending=False).head(5)
            low = v.sort_values().head(3)
            w(f"{src} {BN[b]}: mean {v.mean():.1f}, sd {v.std():.1f}, range {v.min()}-{v.max()}, var/mean {v.var()/v.mean():.2f}; "
              f"most active " + ", ".join(f"{s}-{str(s+1)[2:]} ({n})" for s, n in top.items()) +
              "; least " + ", ".join(f"{s}-{str(s+1)[2:]} ({n})" for s, n in low.items()))
    rng = np.random.default_rng(1)
    for b in BASINS:
        a = st[(st.source == "archive") & (st.basin == b)].events.values
        p = st[(st.source == "proxy") & (st.basin == b)].events.values
        rs = pd.Series(a).corr(pd.Series(p), method="spearman")
        bs = [pd.Series(a[i]).corr(pd.Series(p[i]), method="spearman") for i in (rng.integers(0, NSEAS, NSEAS) for _ in range(NBOOT))]
        w(f"Archive-vs-proxy season counts, {BN[b]}: Spearman {rs:.2f} [{np.nanpercentile(bs,2.5):.2f}, {np.nanpercentile(bs,97.5):.2f}] (n={NSEAS} seasons; descriptive)")
    aa = st[(st.source == "archive") & (st.basin == "atl")].events.values
    ap = st[(st.source == "archive") & (st.basin == "pac")].events.values
    bs = [pd.Series(aa[i]).corr(pd.Series(ap[i]), method="spearman") for i in (rng.integers(0, NSEAS, NSEAS) for _ in range(NBOOT))]
    w(f"Archive Atlantic vs Pacific season counts: Spearman {pd.Series(aa).corr(pd.Series(ap), method='spearman'):.2f} [{np.nanpercentile(bs,2.5):.2f}, {np.nanpercentile(bs,97.5):.2f}]")

    # ---- 3 and 4 distributions
    ad = dist_summary(A, "archive", ["minp", "hf_h", "hf_dist_km", "hf_spd", "deep24", "berg", "lat_on", "lat_mp", "lat_off"])
    pdist = dist_summary(P, "proxy", ["minp", "gust", "hf_h", "hf_spd", "maxdeep", "lat_on", "lat_mp", "lat_off"])
    dd = pd.concat([ad, pdist])
    dd.to_csv(os.path.join(RES, "distributions.csv"), index=False, float_format="%.3f")
    w("\n== Distributions (median [interval]; quartiles; 90th percentile) ==")
    for _, r in dd.iterrows():
        w(f"{r.source} {BN[r.basin]} {r.metric} (n={r.n}): median {r['median']:.2f} [{r.median_lo:.2f}, {r.median_hi:.2f}]  q25 {r.q25:.2f} q75 {r.q75:.2f} p90 {r.p90:.2f}")
    w("\n== Strength thresholds: share of events (class 'low' for archive) ==")
    for src, ev in (("archive", A), ("proxy", P)):
        for b in BASINS:
            d = ev[(ev.basin == b)].minp.dropna()
            w(f"{src} {BN[b]}: minimum pressure < 960 hPa {np.mean(d<960):.3f}, < 950 {np.mean(d<950):.3f}, < 940 {np.mean(d<940):.3f} (n={len(d)})")
    for b in BASINS:
        d = A[(A.basin == b)]
        m = d.berg.notna()
        w(f"Archive {BN[b]}: HF-window deepening measurable for {int(m.sum())}/{len(d)} events; bomb (>=1 Bergeron) share among those {d.bomb[m].astype(bool).mean():.3f} (selected subset, not all events)")
        p = P[(P.basin == b)].maxdeep.dropna()
        w(f"Proxy {BN[b]}: max 24 h deepening >= 1 Bergeron {np.mean(p>=1):.3f} (n={len(p)}; needs a track surviving 24 h)")
    w("\n== Ten deepest archive lows by analysed minimum pressure (unverified against the sheet) ==")
    deep = A[A.cls == "low"].sort_values("minp").head(10)
    for _, r in deep.iterrows():
        w(f"   {r.key}  {r.minp:.0f} hPa  at {int(r.minpat) if pd.notna(r.minpat) else 'NA'}  ({r.lat_mp:.1f}N, {r.lon_mp:.1f}E)")

    # bomb share and HF hours by month
    w("\n== Proxy: share with max 24 h deepening >= 1 Bergeron, by month of first HF fix ==")
    for b in BASINS:
        s = []
        for m in MONTHS:
            x = P[(P.basin == b) & (P.mon_on == m)].maxdeep.dropna()
            s.append(f"{m}: {np.mean(x>=1):.2f} (n={len(x)})")
        w(f"{BN[b]}: " + "; ".join(s))

    # ---- positions
    pos = []
    for src, ev in (("archive", A), ("proxy", P)):
        for b in BASINS:
            for m in MONTHS:
                x = ev[(ev.basin == b) & (ev.mon_on == m)]
                for what, la in (("first_hf", "lat_on"), ("min_pressure", "lat_mp"), ("last_hf", "lat_off")):
                    v = x[la].dropna()
                    pos.append(dict(source=src, basin=b, month=m, point=what, n=len(v), lat_median=v.median(),
                                    lat_q25=v.quantile(.25), lat_q75=v.quantile(.75)))
    pd.DataFrame(pos).to_csv(os.path.join(RES, "latitude_by_month.csv"), index=False, float_format="%.2f")
    w("\n== Median latitude of first HF fix, by month (archive | proxy) ==")
    for b in BASINS:
        for m in MONTHS:
            a = A[(A.basin == b) & (A.mon_on == m)].lat_on
            p = P[(P.basin == b) & (P.mon_on == m)].lat_on
            w(f"{BN[b]} month {m:2d}: archive {a.median():.1f} (n={len(a)}) | proxy {p.median():.1f} (n={len(p)})")
    for src, ev in (("archive", A), ("proxy", P)):
        for b in BASINS:
            d = ev[ev.basin == b]
            w(f"{src} {BN[b]} median position of first HF fix {d.lat_on.median():.1f}N; min-pressure fix {d.lat_mp.median():.1f}N; last HF fix {d.lat_off.median():.1f}N; "
              f"share with first HF fix at or north of 60N {np.mean(d.lat_on>=60):.3f}")

    # ---- boxes
    for src, fx in (("archive", AF), ("proxy", PF)):
        for b in BASINS:
            la, lo, H = box_hours(fx, b)
            df = pd.DataFrame(H, index=la[:-1], columns=lo[:-1])
            df.index.name = "lat_south_edge"
            df.to_csv(os.path.join(RES, f"hf_hours_per_season_{src}_{b}.csv"), float_format="%.3f")
            k = np.unravel_index(H.argmax(), H.shape)
            w(f"{src} {BN[b]} busiest 5x10 deg box: {la[k[0]]:.0f}-{la[k[0]]+5:.0f}N, {lo[k[1]]:.0f} to {lo[k[1]]+10:.0f}E: {H[k]:.1f} HF-centre hours per season; "
              f"total {H.sum():.0f} h per season")

    # ---- simultaneity
    sim = pd.concat([simultaneity(AF, "archive"), simultaneity(PF, "proxy")])
    sim.to_csv(os.path.join(RES, "simultaneous.csv"), index=False, float_format="%.4f")
    w("\n== How many HF lows at once (6-hourly times, Oct-Apr, 22 seasons) ==")
    for _, r in sim.iterrows():
        w(f"{r.source} {BN[r.basin]}: >=1 low {r.share_ge1:.3f}, >=2 {r.share_ge2:.3f}, >=3 {r.share_ge3:.4f}, >=4 {r.share_ge4:.4f}; max {int(r.max_simultaneous)}; mean given any {r.mean_given_any:.2f}")

    # ---- motion
    mo = pd.concat([motion_field(AF).assign(source="archive"), motion_field(PF).assign(source="proxy")])
    mo["speed"] = np.hypot(mo.u, mo.v)
    mo["dir_from_N"] = (np.degrees(np.arctan2(mo.u, mo.v))) % 360       # direction of travel, degrees clockwise from north
    w("\n== Motion of HF lows (consecutive 6-hourly HF fixes) ==")
    for src in ("archive", "proxy"):
        for b in BASINS:
            m = mo[(mo.source == src) & (mo.basin == b)]
            w(f"{src} {BN[b]}: n={len(m)} steps; median speed {m.speed.median():.1f} kt (q25 {m.speed.quantile(.25):.1f}, q75 {m.speed.quantile(.75):.1f}); "
              f"mean eastward {m.u.mean():.1f} kt, northward {m.v.mean():.1f} kt; share moving toward the north-east quadrant {np.mean((m.u>0)&(m.v>0)):.2f}")
    mo.to_csv(os.path.join(RES, "motion_steps.csv.gz"), index=False, float_format="%.3f",
              columns=["source", "basin", "key", "season", "latc", "lonc", "u", "v"])

    # ---- tropical-cyclone link by month (proxy)
    w("\n== Proxy events linked to a tropical cyclone (400 km proximity), by month of first HF fix ==")
    rows = []
    for b in BASINS:
        s = []
        for m in [8, 9, 10, 11, 12, 1, 2, 3, 4, 5]:
            x = P[(P.basin == b) & (P.mon_on == m)]
            if len(x):
                s.append(f"{m}: {x.tc.mean():.2f} ({int(x.tc.sum())}/{len(x)})")
                rows.append(dict(basin=b, month=m, n=len(x), tc=int(x.tc.sum())))
        w(f"{BN[b]}: " + "; ".join(s))
    pd.DataFrame(rows).to_csv(os.path.join(RES, "tc_share_by_month.csv"), index=False)

    open(os.path.join(RES, "atlas.txt"), "w").write("\n".join(out) + "\n")
    A.to_csv(os.path.join(RES, "events_archive.csv"), index=False, float_format="%.3f")
    P.to_csv(os.path.join(RES, "events_proxy.csv"), index=False, float_format="%.3f")
    print("\n".join(out))


if __name__ == "__main__":
    main()
