#!/usr/bin/env python3
"""Build the two small sidecar files that sit next to the ERA5 proxy tracks:

  docs/data/era5-prob.js   window.HF_ERA5_PROB   P(HF within 24 h) at each scored fix
  docs/data/era5-lists.js  window.HF_ERA5_LISTS  the strongest-storm lists

Both are derived data. The tracks they annotate are era5-tracks.js and
era5-null.js (tools/build_era5_tracks.py), so their wire format is untouched.

    python3 tools/build_era5_prob.py \
        --catalog <research>/results/era5_hf_catalog.csv \
        --tracks  <research>/results/era5_hf_catalog_tracks.csv \
        --probs-2004 fix_probs_2004.csv.gz --probs-pre fix_probs_pre2004.csv.gz \
        --strongest strongest_storms.csv --top-gust top_gust_storms_by_era.csv \
        --source <research-branch commit>

P is the PR 12 near-storm model N (no gust predictor), leave-one-season-out,
scored at 00 and 12 UTC fixes only, from research/era5/hf_probability_tracks.
It is a PROXY: the label is pipeline A's gust index reaching 71.7 kt, not the
archive. Before 2004 only the catalog events and their matched null cases are
scored, and those values are for within-era comparison only (decision 1).

Wire format (append-only):
  HF_ERA5_PROB.p[track] = [P*1000 at fix 0, fix 1, ...]  -1 = not scored
  Fix i is at start + 6 h * i, the same indexing as the track files.
  HF_ERA5_LISTS.rows[i] = [list, basin(0 atl,1 pac), rank, track, season,
        date YYYYMMDD, min pressure hPa*10, depth vs monthly norm hPa*10 (null when the table has none),
        gust800 kt*10, tc(0/1), era, name (inferred, may be ""), gust_flag]
  list: "minp" | "depth" | "gust"; era: "" | "1979-2000" | "2004-2025".
"""
import argparse
import csv
import datetime as dt
import gzip
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def t(s):
    return dt.datetime.strptime(s, "%Y%m%d%H")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", required=True)
    ap.add_argument("--tracks", required=True)
    ap.add_argument("--probs-2004", required=True)
    ap.add_argument("--probs-pre", required=True)
    ap.add_argument("--strongest", required=True)
    ap.add_argument("--top-gust", required=True)
    ap.add_argument("--source", required=True)
    ap.add_argument("--outdir", default=os.path.join(ROOT, "docs", "data"))
    a = ap.parse_args()

    cat = {}
    with open(a.catalog, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            cat[r["track"]] = r
    nfix, first = {}, {}
    with open(a.tracks, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            nfix[r["track"]] = nfix.get(r["track"], 0) + 1
            first.setdefault(r["track"], r)

    p = {}
    stats = {"2004": 0, "pre": 0}
    for key, path in (("2004", a.probs_2004), ("pre", a.probs_pre)):
        with gzip.open(path, "rt", newline="", encoding="utf-8") as fh:
            for r in csv.DictReader(fh):
                tid = r["track"]
                if tid not in cat:
                    continue                      # not a catalog track: no fixes on the map
                i = (t(r["time"]) - t(cat[tid]["start"])) // dt.timedelta(hours=6)
                if (t(r["time"]) - t(cat[tid]["start"])) % dt.timedelta(hours=6) or not 0 <= i < nfix[tid]:
                    sys.exit("track %s: scored fix %s is not on the track's 6-hourly grid" % (tid, r["time"]))
                row = p.setdefault(tid, [-1] * nfix[tid])
                v = round(float(r["P_N"]) * 1000)
                if row[i] not in (-1, v):
                    sys.exit("track %s fix %d scored twice with different P" % (tid, i))
                row[i] = v
                stats[key] += 1
    for tid in p:
        if first[tid]["time"] != cat[tid]["start"]:
            sys.exit("track %s: first fix is not the start" % tid)

    meta = {"what": "ERA5 proxy P(HF within 24 h), model N, leave-one-season-out, at the 00/12 UTC fixes of the catalog tracks "
                    "(research/era5/hf_probability_tracks). Pipeline A label, not the archive. Before 2004 within-era only.",
            "source": a.source, "tracks": len(p), "scored_fixes": sum(stats.values()),
            "fields": ["track -> [P*1000 per fix from start, 6-hourly; -1 not scored]"]}
    out = os.path.join(a.outdir, "era5-prob.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("/* generated by tools/build_era5_prob.py - do not edit. ERA5 PROXY, not the archive. */\n")
        fh.write("window.HF_ERA5_PROB = " + json.dumps({"meta": meta, "p": p}, separators=(",", ":")) + ";\n")
    print("P: %d tracks, %d scored fixes (2004+ %d, pre-2004 %d)  %.2f MB -> %s"
          % (len(p), sum(stats.values()), stats["2004"], stats["pre"], os.path.getsize(out) / 1e6, out))

    rows = []
    with open(a.strongest, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            rows.append([("minp" if r["rank_by"] == "minp" else "depth"), 0 if r["basin"] == "atl" else 1,
                         int(r["rank"]), int(r["track"]), int(r["season"]), int(r["date_minp"] or r["peak_time"][:8]),
                         round(float(r["minp"]) * 10), round(float(r["anom_clim"]) * 10) if r["anom_clim"] else None,
                         round(float(r["gust800_kt"]) * 10), 1 if r["tc"] == "True" else 0, "",
                         r["name_inferred"], r["gust_flag"]])
    with open(a.top_gust, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            rows.append(["gust", 0 if r["basin"] == "atl" else 1, int(r["rank"]), int(r["track"]),
                         0, int(r["date"]), round(float(r["min_mslp_hpa"]) * 10), 0,
                         round(float(r["gust_index_kt"]) * 10), 1 if r["tc_linked"] == "True" else 0,
                         r["era"].split()[-1], "", ""])
    for r in rows:                                  # the gust file has no season column: take it from the date
        if r[0] == "gust":
            y, m = divmod(r[5], 10000)[0], divmod(r[5], 100)[0] % 100
            r[4] = y if m >= 6 else y - 1
    meta = {"what": "ERA5 proxy strongest storms. minp/depth: top 25 per basin over 1979-2025 by minimum central pressure "
                    "and by depth against the monthly climatology (research/era5/hf_probability_tracks). gust: top 25 gust "
                    "indices ranked WITHIN era only, 1979-2000 and 2004-2025 (research/era5/gust_climo). Storm names are "
                    "inferred from date and position.",
            "source": a.source, "rows": len(rows)}
    out = os.path.join(a.outdir, "era5-lists.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("/* generated by tools/build_era5_prob.py - do not edit. ERA5 PROXY, not the archive. */\n")
        fh.write("window.HF_ERA5_LISTS = " + json.dumps({"meta": meta, "rows": rows}, separators=(",", ":")) + ";\n")
    on_map = sum(1 for r in rows if str(r[3]) in cat)
    print("lists: %d rows (%d with a track on the map) %.3f MB -> %s" % (len(rows), on_map, os.path.getsize(out) / 1e6, out))


if __name__ == "__main__":
    main()
