#!/usr/bin/env python3
"""Build docs/data/era5-tracks.js: the ERA5 proxy hurricane-force-equivalent
tracks (pipeline A, research/era5/hf_history) in a compact form the map can
draw. Derived data only; the research code stays on the research branch.

    python3 tools/build_era5_tracks.py \
        --catalog  <research>/results/era5_hf_catalog.csv \
        --tracks   <research>/results/era5_hf_catalog_tracks.csv \
        --source   <commit of the research branch the two files came from>

Both inputs are on the integration branch (claude/exciting-fermat-8vcvgq),
not on main, so pass their paths (e.g. from `git show <branch>:<path> > file`).
Only the catalog's "event" rows are kept; the matched null cases are not.

Wire format (append-only; do not reorder fields):
  HF_ERA5.ev[i] = [track, basin(0 atl, 1 pac), season, start YYYYMMDDHH,
                   p_hf*1000, peak gust800 kt*10, min pressure hPa*10,
                   flat fixes: lat*4, lon*4 (-180..180), msl hPa, gust800 kt, ...]
Fixes are 6-hourly from `start` (checked), so no per-fix time is stored.

This is an ERA5 PROXY: a cyclone whose ERA5 fields look like the ones OPC
warned for as hurricane force. It is not the archive. Counts before 2001-02
are for within-era comparison only (STATUS.md, decision 1).
"""
import argparse
import csv
import datetime as dt
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THRESHOLD_KT = 71.7


def hours(t):
    return dt.datetime.strptime(t, "%Y%m%d%H")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", required=True)
    ap.add_argument("--tracks", required=True)
    ap.add_argument("--source", required=True, help="research-branch commit the inputs came from")
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "data", "era5-tracks.js"))
    a = ap.parse_args()

    events = {}
    with open(a.catalog, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            if r["role"] == "event":
                events[r["track"]] = r
    fixes = {k: [] for k in events}
    with open(a.tracks, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            if r["track"] in fixes:
                fixes[r["track"]].append(r)

    out, nfix = [], 0
    for tid, r in sorted(events.items(), key=lambda kv: (kv[1]["start"], int(kv[0]))):
        fx = fixes[tid]
        if not fx:
            sys.exit("event %s has no fixes" % tid)
        if fx[0]["time"] != r["start"]:
            sys.exit("event %s: first fix %s != start %s" % (tid, fx[0]["time"], r["start"]))
        for p, q in zip(fx, fx[1:]):
            if hours(q["time"]) - hours(p["time"]) != dt.timedelta(hours=6):
                sys.exit("event %s: fixes are not 6-hourly at %s" % (tid, q["time"]))
        flat = []
        for f in fx:
            lon = float(f["lon"])
            lon = lon - 360.0 if lon > 180 else lon
            flat += [round(float(f["lat"]) * 4), round(lon * 4), round(float(f["msl"])), round(float(f["g800"]))]
        nfix += len(fx)
        out.append([int(tid), 0 if r["basin"] == "atl" else 1, int(r["season"]), int(r["start"]),
                    round(float(r["p_hf"]) * 1000), round(float(r["gust800_kt"]) * 10),
                    round(float(r["minp"]) * 10), flat])
    meta = {
        "what": "ERA5 proxy hurricane-force-equivalent tracks, pipeline A (gust index, research/era5/hf_history)",
        "source": a.source,
        "threshold_kt": THRESHOLD_KT,
        "events": len(out),
        "fixes": nfix,
        "fields": ["track", "basin(0 atl,1 pac)", "season", "start", "p_hf*1000", "peak_gust800_kt*10",
                   "minp_hPa*10", "fixes[lat*4,lon*4,msl_hPa,gust800_kt]*n"],
    }
    with open(a.out, "w", encoding="utf-8") as fh:
        fh.write("/* generated by tools/build_era5_tracks.py - do not edit. ERA5 PROXY, not the archive. */\n")
        fh.write("window.HF_ERA5 = " + json.dumps({"meta": meta, "ev": out}, separators=(",", ":")) + ";\n")
    print("events %d  fixes %d  %.2f MB -> %s" % (len(out), nfix, os.path.getsize(a.out) / 1e6, a.out))


if __name__ == "__main__":
    main()
