#!/usr/bin/env python3
"""Build docs/data/era5-allprob.js: every ERA5 track the P(HF) tables score.

    python3 tools/build_era5_allprob.py \
        --probs-2004 fix_probs_2004.csv.gz --probs-pre fix_probs_pre2004.csv.gz \
        --source "research/era5/hf_probability_tracks/results at <commit>"

Inputs are the per-fix tables of research/era5/hf_probability_tracks (also in
the project folder hf-probability-tracks/). P is the PR 12 near-storm model N
(no gust predictor), leave-one-season-out for 2004-05 onward; the 1979-2003
values come from the same model fitted on 2004+ and applied to the catalog
tracks. It is a PROXY: the label is pipeline A's gust index reaching 71.7 kt in
ERA5, not the archive, and P is a model output, not an observation.

Coverage is whatever the tables hold, not every cyclone: 2004-2025 every low
with a scored 00/12 UTC fix (36,598 tracks), and before 2004 only the catalog
events and their matched null cases (4,311 tracks); the other 1979-2003 lows
have no committed fixes. This sidecar is separate from era5-prob.js, which
annotates the 6-hourly catalog tracks.

Wire format (append-only):
  HF_ERA5_ALLP.t[i] = [track, basin(0 atl,1 pac), season, kind, t0, f]
    kind: 0 = 2004-2025 low, 1 = 1979-2003 catalog event, 2 = 1979-2003 matched null
    t0:   first fix time as 12-hour steps since 1979-01-01 00 UTC
    f:    flat, 4 numbers per fix: dt (12-hour steps since the previous fix; 0 for
          the first), dlat*4, dlon*4 (previous fix to this one, longitude change
          taken the short way; the first is absolute, longitude wrapped to
          -180..180), P*1000 (model N).
"""
import argparse
import datetime as dt
import gzip
import json
import os

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EPOCH = dt.datetime(1979, 1, 1)


def steps12(s):
    """YYYYMMDDHH ints -> 12-hour steps since 1979-01-01 00 UTC."""
    t = pd.to_datetime(s.astype(str), format="%Y%m%d%H")
    return ((t - EPOCH).dt.total_seconds() // (12 * 3600)).astype(int).to_numpy()


def encode(d, kind_of):
    out = []
    d = d.sort_values(["track", "time"])
    for track, g in d.groupby("track", sort=True):
        st = steps12(g["time"])
        lat4 = np.rint(g["lat"].to_numpy() * 4).astype(int)
        lon = ((g["lon"].to_numpy() + 180) % 360) - 180
        lon4 = np.rint(lon * 4).astype(int)
        p = np.clip(np.rint(g["P_N"].to_numpy() * 1000), 0, 1000).astype(int)
        f = []
        for i in range(len(g)):
            if i == 0:
                f += [0, int(lat4[0]), int(lon4[0]), int(p[0])]
            else:
                dl = lon4[i] - lon4[i - 1]
                dl = (dl + 720) % 1440 - 720            # the short way round
                f += [int(st[i] - st[i - 1]), int(lat4[i] - lat4[i - 1]), int(dl), int(p[i])]
        basin = 0 if g["basin"].iloc[0] == "atl" else 1
        out.append([int(track), basin, int(g["season"].iloc[0]), kind_of(g), int(st[0]), f])
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--probs-2004", required=True)
    ap.add_argument("--probs-pre", required=True)
    ap.add_argument("--source", required=True)
    ap.add_argument("--outdir", default=os.path.join(ROOT, "docs", "data"))
    a = ap.parse_args()

    d4 = pd.read_csv(a.probs_2004)
    dp = pd.read_csv(a.probs_pre)
    t = encode(d4, lambda g: 0) + encode(dp, lambda g: 1 if g["role"].iloc[0] == "event" else 2)
    nfix = len(d4) + len(dp)
    meta = {
        "what": "ERA5 proxy P(HF within 24 h), model N, at the 00/12 UTC fixes of every track the research tables score "
                "(research/era5/hf_probability_tracks). Pipeline A label (gust index at 71.7 kt), not the archive; a model "
                "output, not an observation. 2004-2025 every scored low; 1979-2003 only the catalog events and their matched "
                "null cases. Before 2004 within-era only.",
        "source": a.source, "tracks": len(t), "fixes": nfix,
        "by_kind": {"low_2004_2025": int(sum(1 for r in t if r[3] == 0)), "event_pre2004": int(sum(1 for r in t if r[3] == 1)),
                    "null_pre2004": int(sum(1 for r in t if r[3] == 2))},
        "epoch": "1979-01-01 00 UTC, 12-hour steps",
    }
    os.makedirs(a.outdir, exist_ok=True)
    path = os.path.join(a.outdir, "era5-allprob.js")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("/* generated by tools/build_era5_allprob.py - do not edit. ERA5 PROXY model output, not an observation. */\n")
        fh.write("window.HF_ERA5_ALLP = " + json.dumps({"meta": meta, "t": t}, separators=(",", ":")) + ";\n")
    size = os.path.getsize(path)
    gz = len(gzip.compress(open(path, "rb").read()))
    print("%s: %d tracks, %d fixes, %.2f MB (%.2f MB gzipped)" % (path, len(t), nfix, size / 1e6, gz / 1e6))


if __name__ == "__main__":
    main()
