#!/usr/bin/env python3
"""Build docs/data/gust-climo.js: the ERA5 gust climatology for the map.

Derived data only. The grid comes from research/era5/gust_climo (analyse.py,
gust_climo_grid.npz on the research branch): ARCO-ERA5 instantaneous 10 m gust
at 00 and 12 UTC, 1 October to 30 April, seasons 2004-05 to 2025-26 (9,338
times), ocean points only. It is a PROXY, not an observation, and ERA5 reads
low in extreme storms. Gust is instantaneous and 12-hourly, so every number is
a lower bound on the true maximum, and the late-summer tropical-cyclone season
is not sampled.

    python3 tools/build_gust_climo.py --grid <gust_climo_grid.npz> --source <commit>

The 0.25 degree grid is reduced to 1 degree blocks (mean of the ocean cells in
a block; a block exists if any of its 16 cells is ocean, so coastal blocks mix
ocean cells only) over lat 20-80N and the two basin windows the rest of the
map uses (Atlantic 100W-30E, Pacific 120E-110W), to keep the file small.

Wire format (append-only):
  HF_GUST_CLIMO.win[basin] = {lat0, lon0, dlat, dlon, nlat, nlon, f: {field: [..]}}
  row-major from (lat0, lon0), south to north then west to east, -1 = no ocean.
  fields: annmax  mean annual maximum gust, kt * 2   (rounded to 0.5 kt)
          f50, f64, f717  share of sampled times with gust at or above 50, 64,
          71.7 kt, in units of 0.01 %   (so 150 = 1.5 %)
"""
import argparse
import json
import os

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WINDOWS = {"atl": (-100, 30), "pac": (120, 250)}
LAT0, LAT1 = 20, 80
FIELDS = (("annmax", None), ("f50", 50.0), ("f64", 64.0), ("f717", 71.7))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--grid", required=True)
    ap.add_argument("--source", required=True)
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "data", "gust-climo.js"))
    a = ap.parse_args()
    z = np.load(a.grid, allow_pickle=True)
    lat, lon = z["lat"].astype(float), z["lon"].astype(float)
    thr = list(map(float, z["freq_thresholds_kt"]))
    assert abs(lat[1] - lat[0] - 0.25) < 1e-6 or abs(lat[0] - lat[1] - 0.25) < 1e-6, "expected a 0.25 degree grid"
    src = {"annmax": z["annual_max_mean_kt"].astype(float)}
    for name, t in FIELDS[1:]:
        src[name] = z["freq"][int(np.argmin(np.abs(np.array(thr) - t)))].astype(float)
    order = np.argsort(lat)
    lat = lat[order]
    for k in src:
        src[k] = src[k][order]
    win = {}
    summary = {}
    for b, (w0, w1) in WINDOWS.items():
        lat_idx = [int(np.argmin(np.abs(lat - (LAT0 + d)))) for d in range(0, LAT1 - LAT0 + 1)]
        lon_idx_deg = list(range(w0, w1 + 1))
        # grid longitudes run 0..359.75; a window in -180..180 wraps
        lon_idx = [int(np.argmin(np.abs(lon - (d % 360)))) for d in lon_idx_deg]
        def cols(j):                       # the 4 grid columns of a block; wraps through the 0/360 seam
            return np.arange(lon_idx[j], lon_idx[j] + 4) % lon.size
        f = {}
        for name, _ in FIELDS:
            A = src[name]
            out = np.full((len(lat_idx) - 1, len(lon_idx) - 1), -1.0)
            for i in range(len(lat_idx) - 1):
                rows = A[lat_idx[i]:lat_idx[i] + 4]
                for j in range(len(lon_idx) - 1):
                    v = rows[:, cols(j)]
                    v = v[v >= 0]
                    if v.size:
                        out[i, j] = v.mean()
            if name == "annmax":
                enc = np.where(out < 0, -1, np.rint(out * 2)).astype(int)
            else:
                enc = np.where(out < 0, -1, np.rint(out * 10000)).astype(int)
            f[name] = enc.ravel().tolist()
            summary[(b, name)] = (out.max(), int((out >= 0).sum()))
        win[b] = {"lat0": LAT0, "lon0": w0, "dlat": 1, "dlon": 1, "nlat": LAT1 - LAT0, "nlon": w1 - w0, "f": f}
    meta = {"what": "ERA5 PROXY gust climatology (research/era5/gust_climo): instantaneous 10 m gust at 00 and 12 UTC, "
                    "1 October to 30 April, seasons 2004-05 to 2025-26, ocean only, 1 degree blocks. ERA5 reads low in "
                    "extreme storms; a lower bound on true maxima.",
            "source": a.source, "n_times": int(z["n_times"]), "seasons": 22,
            "fields": ["annmax: kt*2", "f50/f64/f717: share of times at or above 50/64/71.7 kt, 0.01 % units"]}
    with open(a.out, "w", encoding="utf-8") as fh:
        fh.write("/* generated by tools/build_gust_climo.py - do not edit. ERA5 PROXY, not direct observation. */\n")
        fh.write("window.HF_GUST_CLIMO = " + json.dumps({"meta": meta, "win": win}, separators=(",", ":")) + ";\n")
    print("%.3f MB -> %s" % (os.path.getsize(a.out) / 1e6, a.out))
    for k, v in sorted(summary.items()):
        print(k, "max %.4g" % v[0], "ocean blocks", v[1])


if __name__ == "__main__":
    main()
